{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nxt-helder.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nxt-helder.fullname" $ }}-web
                port:
                  number: {{ $.Values.web.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "nxt-helder.fullname" $ }}-server
                port:
                  number: {{ $.Values.server.service.port }}
    {{- end }}
{{- end }}
